checks:
  php: true
  javascript: false
  css: false

build:
  nodes:
    analysis:
      tests:
        override: [php-scrutinizer-run]
      cache:
        directories:
          - vendor/
filter:
  paths: ["src/*"]

tools:
  external_code_coverage: true
