<?php


namespace Firesphere\SolrSearch\Tests;


use Firesphere\SolrSearch\Helpers\Synonyms;
use Firesphere\SolrSearch\Indexes\BaseIndex;
use Firesphere\SolrSearch\Services\SchemaService;
use \TestIndex;
use SilverStripe\Core\Injector\Injector;
use SilverStripe\Dev\SapphireTest;
use Solarium\Core\Client\Client;

class BaseIndexTest extends SapphireTest
{
    /**
     * @var BaseIndex
     */
    protected $index;

    protected function setUp()
    {
        $this->index = Injector::inst()->get(TestIndex::class);
        return parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testConstruct()
    {
        $this->assertInstanceOf(Client::class, $this->index->getClient());
    }

    public function testGetSynonyms()
    {
        $this->assertEquals(Synonyms::getSynonymsAsString(), $this->index->getSynonyms());

        $this->assertEmpty($this->index->getSynonyms(false));
    }
}